// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FriendshipButtonController from "./friendship_button_controller"
application.register("friendship-button", FriendshipButtonController)

import FriendshipSubscriptionController from "./friendship_subscription_controller"
application.register("friendship-subscription", FriendshipSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LastMessageController from "./last_message_controller"
application.register("last-message", LastMessageController)

import QueueForLoungeController from "./queue_for_lounge_controller"
application.register("queue-for-lounge", QueueForLoungeController)

import ReviewButtonsController from "./review_buttons_controller"
application.register("review-buttons", ReviewButtonsController)

import SessionLanguageController from "./session_language_controller"
application.register("session-language", SessionLanguageController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import VideoCallController from "./video_call_controller"
application.register("video-call", VideoCallController)
